[project]
name = "pv251"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "country-converter>=1.3",
    "notebook>=7.2.2",
    "pandas>=2.2.3",
    "pycountry>=24.6.1",
]
